StarridgeCity_EldonsHouse_MapScripts::
	.byte 0


StarridgeCity_EventScript_Trade_Honedge::
# 4 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	lock
# 5 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	faceplayer
# 6 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	release
	return


StarridgeCity_Text_Trade_Honedge_AskToTrade::
# 9 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	.string "Hey, kid. Do you ever trade Pokémon with\n"
	.string "people?\p"
	.string "It's always fun to see what kind of\n"
	.string "bonds form with a new partner.\p"
	.string "Why do I ask?\n"
	.string "You see, I've got this Honedge and he's\l"
	.string "a trusty blade, but...\p"
	.string "I think he's looking for a new\n"
	.string "adventure.\p"
	.string "Maybe you could be the one to guide him\n"
	.string "to his next challenge.\p"
	.string "If you could trade me a rare Pokemon\n"
	.string "like Dunsparce I'd trade you him.\p"
	.string "What do you say?$"

StarridgeCity_Text_Trade_Honedge_AfterTrade::
# 20 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	.string "Sh'ding is in good hands, I can tell.\p"
	.string "He's been with me for a while, but I\n"
	.string "think he'll grow even stronger with you.\p"
	.string "Treat him well, yeah?\p"
	.string "And don't worry about Dunsparce--it'll\n"
	.string "fit in perfectly here.$"

StarridgeCity_Text_Trade_Honedge_After::
# 28 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	.string "I've finally got a Dunsparce! I can't\n"
	.string "wait to see what it can do!$"

StarridgeCity_Text_Trade_Honedge_Refuse::
# 32 "data/maps/StarridgeCity_EldonsHouse/scripts.pory"
	.string "What? you changed your mind\p"
	.string "Ah, no worries!\n"
	.string "Maybe you'll change your mind later.$"
