
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                                0
#define PARTNER_STEVEN                              1
#define PARTNER_HOLLY_STARRIDGE_RUINS_TURTWIG       2
#define PARTNER_HOLLY_STARRIDGE_RUINS_FENNEKIN      3
#define PARTNER_HOLLY_STARRIDGE_RUINS_QUAXLY        4
#define PARTNER_CADEN_STARRIDGE_RUINS_TURTWIG       5
#define PARTNER_CADEN_STARRIDGE_RUINS_FENNEKIN      6
#define PARTNER_CADEN_STARRIDGE_RUINS_QUAXLY        7

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
