StarridgeRuins_1F_MapScripts::
	.byte 0


StarridgeRuins_1F_Text_Grunts_GruntA_1::
# 3 "data/maps/StarridgeRuins_1F/scripts.pory"
	.string "Can't you see we're busy here?\p"
	.string "We're trying to find the treasure in\n"
	.string "this place!\p"
	.string "Why don't you go mind the business that\n"
	.string "pays you, huh?$"

StarridgeRuins_1F_Text_Grunts_GruntB_1::
# 9 "data/maps/StarridgeRuins_1F/scripts.pory"
	.string "Hey, wait a minute!\p"
	.string "You're the kid that beat me in that\n"
	.string "stupid nerd club!\p"
	.string "I'm not going to let you get in my way\n"
	.string "again!\p"
	.string "I've got backup this time, so you're\n"
	.string "going down!$"
